### ISSUE TITLE
What do preprocessor and data_to_series function and exactly do?

### ISSUE THREAD

**Issue by manmeet3591** [jweyn/DLWP#1]
I am trying to implement DLWP for my data. I am trying to understand what preprocessor and data_to_series are trying to do? Please correct me if I am wrong. Is the function data_to_series just converting the time dimension to sample ?

**Comment by jweyn** [comment]
Yes, it's actually pretty simply reformatting data from the raw files downloaded from CFS/ERA5 into a continuous time series. It probably isn't actually necessary to use this if you are familiar with and comfortable manipulating xarray datasets. It does write data with the mean and std removed, if that is useful to you.

By the way, I highly recommend looking at the newer repository on this subject, [DLWP-CS](https://github.com/jweyn/DLWP-CS).

**Comment by manmeet3591** [comment]
Thank you for the explanation @jweyn
